### ISSUE TITLE
phar运行时项目时，File.php遍历目录会遍历linux根路径

### ISSUE THREAD

**Issue by ghost** [easy-swoole/utility#5]
环境：docker-php：7.2.17
swoole版本：3.2.1
问题位置：vendor/easyswoole/utility/src/File.php  219行。
问题：生成phar文件并运行，在遍历App目录时，
           路径是“phar:///www/easyswoole/easyswoole.phar/App”，所以在使用realpath方法时结果 
           是false，导致会循环linux根目录

**Comment by kiss291323003** [comment]
好的，处理中
